import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import EditNavbar from "@/components/editor/EditNavbar";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <EditNavbar/>
      <main className="container py-10">{children}</main>
      <Toaster />
    </section>
  );
}
