import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Providers } from "@/redux/provider";
import { Toaster } from "@/components/ui/toaster";
import DarkProvider from "@/app/darkprovider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkProvider>
          <Providers>
            <Navbar />
            <main className="container py-10">{children}</main>
          </Providers>
        </DarkProvider>
      </body>
    </html>
  );
}
